---
# Role dependencies
collections:
  - name: community.general
    version: ">=7.0.0"

roles:
  - src: https://github.com/willshersystems/ansible-sshd.git
    name: willshersystems.sshd
  - src: https://github.com/FoxySimon/ansible-role-base.git
    name: ansible-role-base
