- name: Create base user
  become: true
  tags: base,base-user
  ansible.builtin.user:
    name: "{{ base_user }}"
    create_home: "{{ base_user_create_home }}"
    state: "{{ base_user_state }}"

- name: Add user to admin groups
  when: base_user_state == "present"
  block:
    - name: Determine available groups
      tags: base,base-groups
      ansible.builtin.getent:
        database: group
      register: available_groups

    - name: Add user to admin groups if they exist
      tags: base,base-groups
      ansible.builtin.user:
        name: "{{ base_user }}"
        groups: "{{ item }}"
        append: true
      loop: "{{ base_groups + base_groups_extra }}"
      when: item in ansible_facts.getent_group

- name: Configure sudo NOPASSWD access for package management
  tags: base,base-sudo
  community.general.sudoers:
    name: "{{ base_user }}_nopasswd"
    commands: "{{ base_sudo_nopasswd_commands + base_sudo_nopasswd_commands_extra }}"
    user: "{{ base_user }}"
    runas: ALL
    nopassword: true
    state: present

- name: Configure ansible-pull cron job
  when: base_cron_enabled | bool
  ansible.builtin.cron:
    name: "ansible-pull automatic update"
    user: "{{ base_user }}"
    minute: "{{ base_cron_schedule.split(' ')[0] }}"
    hour: "{{ base_cron_schedule.split(' ')[1] }}"
    day: "{{ base_cron_schedule.split(' ')[2] }}"
    month: "{{ base_cron_schedule.split(' ')[3] }}"
    weekday: "{{ base_cron_schedule.split(' ')[4] }}"
    job: >-
      /usr/bin/ansible-pull -U https://github.com/{{ base_cron_repo }} 
      -C {{ base_cron_version }} {{ base_cron_playbook }}
      2>&1 | logger -t {{ base_cron_tag }}
