- name: Create base user
  become: true
  tags: base,base-user
  ansible.builtin.user:
    name: "{{ base_user }}"
    create_home: "{{ base_user_create_home }}"
    state: "{{ base_user_state }}"

- name: Add user to admin groups
  when: base_user_state == "present"
  block:
    - name: Determine available groups
      tags: base,base-groups
      ansible.builtin.getent:
        database: group
      register: available_groups

    - name: Add user to admin groups if they exist
      tags: base,base-groups
      ansible.builtin.user:
        name: "{{ base_user }}"
        groups: "{{ item }}"
        append: true
      loop: "{{ base_groups + base_groups_extra }}"
      when: item in ansible_facts.getent_group
